### ISSUE TITLE
ngs_tools.gtf.Segment.SegmentError: Invalid segment with kallisto aligner

### ISSUE THREAD

**Issue by zhewa** [nf-core/scrnaseq#119]
### Description of the bug

An error occurred with kallisto aligner during the generation of reference index. The error occurred in the call to `ngs_tools/gtf/Segment.py`. It seems to have something to do with segment of zero length. I am using GRCh38.p14 fasta and gtf files from NCBI with appended ERCC transcripts. An update to required `kb_python` version in

https://github.com/nf-core/scrnaseq/blob/0bf83a897efcdc38ca3d0a7b8d0bd46e668d048a/modules/nf-core/modules/kallistobustools/ref/main.nf#L5-L8

and
https://github.com/nf-core/scrnaseq/blob/0bf83a897efcdc38ca3d0a7b8d0bd46e668d048a/modules/local/kallistobustools_count.nf#L5-L8

 will probably fix this.
Lioscro/ngs-tools#30

### Command used and terminal output

```console
## Workflow execution completed unsuccessfully

Error executing process > 'NFCORE_SCRNASEQ:SCRNASEQ:KALLISTO_BUSTOOLS:KALLISTOBUSTOOLS_REF (GCF_000001405.40_GRCh38.p14_genomic_ERCC92.fna.gz)'

Caused by:
  Missing output file(s) `kb_ref_out.idx` expected by process `NFCORE_SCRNASEQ:SCRNASEQ:KALLISTO_BUSTOOLS:KALLISTOBUSTOOLS_REF (GCF_000001405.40_GRCh38.p14_genomic_ERCC92.fna.gz)`

Command executed:

  kb \
      ref \
      -i kb_ref_out.idx \
      -g t2g.txt \
      -f1 cdna.fa \
      --workflow standard \
      GCF_000001405.40_GRCh38.p14_genomic_ERCC92.fna.gz \
      GCF_000001405.40_GRCh38.p14_genomic_ERCC92_no_gene_bar.gtf.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SCRNASEQ:SCRNASEQ:KALLISTO_BUSTOOLS:KALLISTOBUSTOOLS_REF":
      kallistobustools: $(echo $(kb --version 2>&1) | sed 's/^.*kb_python //;s/positional arguments.*$//')
  END_VERSIONS

Command exit status:
  0

Command output:
  (empty)

Command error:
  [2022-06-28 15:32:18,920]    INFO [ref] Preparing GCF_000001405.40_GRCh38.p14_genomic_ERCC92.fna.gz, GCF_000001405.40_GRCh38.p14_genomic_ERCC92_no_gene_bar.gtf.gz
  [2022-06-28 15:34:07,208]   ERROR [main] An exception occurred
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/kb_python/main.py", line 856, in main
      COMMAND_TO_FUNCTION[args.command](parser, args, temp_dir=temp_dir)
    File "/usr/local/lib/python3.9/site-packages/kb_python/main.py", line 168, in parse_ref
      ref(
    File "/usr/local/lib/python3.9/site-packages/ngs_tools/logging.py", line 62, in inner
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.9/site-packages/kb_python/ref.py", line 393, in ref
      gene_infos, transcript_infos = ngs.gtf.genes_and_transcripts_from_gtf(
    File "/usr/local/lib/python3.9/site-packages/ngs_tools/gtf/__init__.py", line 190, in genes_and_transcripts_from_gtf
      introns = exons.invert(transcript_interval)
    File "/usr/local/lib/python3.9/site-packages/ngs_tools/gtf/SegmentCollection.py", line 108, in invert
      Segment(self._segments[i].end, self._segments[i + 1].start)
    File "/usr/local/lib/python3.9/site-packages/ngs_tools/gtf/Segment.py", line 27, in __init__
      raise SegmentError(f'Invalid segment [{start}:{end})')
  ngs_tools.gtf.Segment.SegmentError: Invalid segment [1095094:1095094)

Work dir:
  s3://***

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

### System information

- Nextflow version: 22.04.3
- Hardware: Cloud
- Executor: awsbatch
- Container engine: 
- OS: CentOS Linux
- Version of nf-core/scrnaseq: 2.0.0

**Comment by ameynert** [comment]
Fixed in #120
