### ISSUE TITLE
cellranger_count.py: capture stderr and stdout

### ISSUE THREAD

**Issue by nick-youngblut** [nf-core/scrnaseq#341]
### Description of feature

[cellranger_count.py](https://github.com/nf-core/scrnaseq/blob/master/modules/nf-core/cellranger/count/templates/cellranger_count.py) currently just uses `subprocess.run` for running `cellranger count`, but it does not capture and write out the subprocess stdout and stderr, so all that is returned to the user during a failed job is:

```
Traceback (most recent call last):
  File "/home/nickyoungblut/dev/nextflow/scrnaseq/work/8a/e399f792d79e21d811f4d2698751fa/.command.sh", line 57, in <module>
    run(
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cellranger', 'count', '--id', 'pbmc8k_s1', '--fastqs', 'fastq_all', '--transcriptome', 'refdata-gex-GRCh38-2024-A', '--localcores', '12', '--localmem', '72', '--chemistry', 'SC3Pv2', '--create-bam', 'true', '--expect-cells', '10000']' returned non-zero exit status 1.
```

It would be helpful if stderr and stdout were captured and returned. For example:

```python
result = run(
    # fmt: off
    [
        "cellranger", "count",
        "--id", "${prefix}",
        "--fastqs", str(fastq_all),
        "--transcriptome", "${reference.name}",
        "--localcores", "${task.cpus}",
        "--localmem", "${task.memory.toGiga()}",
        *shlex.split("""${args}""")
    ],
    # fmt: on
    check=True,
    capture_output=True,
    text=True  # to get the output as strings
)

# Access the stdout and stderr
stdout = result.stdout
stderr = result.stderr

# Write the stdout and stderr
[...]
```

An alternative:

```python
from subprocess import run, CalledProcessError
import shlex

def run_subprocess(command):
    try:
        result = run(
            shlex.split(command),
            check=True,
            capture_output=True,
            text=True
        )
        return result.stdout, result.stderr
    except CalledProcessError as e:
        print(f"Command '{e.cmd}' failed with return code {e.returncode}")
        print(f"stdout: {e.stdout}")
        print(f"stderr: {e.stderr}")
        raise

# Example usage
command = "cellranger count --id sample_id --fastqs ./fastq_all --transcriptome reference --localcores 4 --localmem 16"
stdout, stderr = run_subprocess(command)
```

**Comment by nick-youngblut** [comment]
Also, it appears that since `cellranger count` is called from within the `cellranger_count.py` job, a 137 exit status (lack of memory) for the `cellranger count` job will be "reported" by the `cellranger_count.py` job as just an exit status of 1. 

This is important for retrying processes with escalated resources:

```
    errorStrategy = { task.exitStatus in ((130..145) + 104) ? 'retry' : 'finish' }
    maxRetries    = 1
    maxErrors     = '-1'
```

...since exit values of 1 will not trigger a retry.

**Comment by grst** [comment]
Thanks for raising the issue, agree stderr/stdout and exit code should be forwarded. 
This should be fixed at the `nf-core/modules` level and likely also affects the spaceranger and cellranger multi modules that share the python script. 

I will follow up on this eventually, but I have only very limited time I can put into nf-core at the moment -- so if you want to speed it up a PR to modules would be appreciated :)

**Comment by nick-youngblut** [comment]
@grst do you know if `cellranger count` actually returns at 137 exit if there is a lack of memory for the job?

I am using `-process.scratch ram-disk`, which requires more memory for the job, but the current release of the `cellranger-count` nf-core module just returns an exit of 1, so the job will never retry with more memory:

```
    withLabel:process_high {
        cpus   = { check_max( 12    * task.attempt, 'cpus'    ) }
        memory = { check_max( 72.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 16.h  * task.attempt, 'time'    ) }
    }
```

**Comment by grst** [comment]
No idea. But it shouldn't be hard to capture the exit code from the subprocess call and then do `sys.exit(exitcode)` in Python.
